### ISSUE TITLE
SyntaxError on python3

### ISSUE THREAD

**Issue by abc19899** [wooparadog/pystack#6]
in python3: 
[root@android_tx_baolei bin]# pstack3 15632
Traceback (most recent call last):
  File "/usr/bin/pstack3", line 9, in <module>
    load_entry_point('pstack==0.6', 'console_scripts', 'pstack')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/stack.py", line 70
    os.chmod(tmp_path, 0777)
                          ^
SyntaxError: invalid token

**Comment by lightfish-zhang** [comment]
me too, how to solve it?

**Comment by tonyseek** [comment]
The latest release `pystack-debugger==0.7.1` fixes the syntax errors in Python 3. But the Python 3 support is still working in progress.

For now, it is impossible to inspect thread stack of a Python 3 process with pystack.
